#!/usr/bin/env python3

class Word:

	# def __init__(self, word):
	# 	self.word = word

	def word_max(self, word):
		if len(word) == 1:
			return word[0]
		elif len(word) == 2:
			if word[0] > word[1]:
				return word[0]
			else:
				return word[1]
		else:
			maxs = ""
			for i in range(0, len(self.word)//2):
				if word[i] > word[len(self.word) - 1 - i]:
					maxs = maxs + word[i]
				else:
					maxs = maxs + word[len(self.word - 1 - i)]


